export const projects = [
  {
    image: "abode.png",
    title: "Abode Luxury",
    desc: "I built this web app for a client who owns a Real Estate Development Agency in Nigeria, based in Abuja",
    href: "https://abodeluxuryng.com",
    stacks: "Next JS, SASS, redux",
  },
  {
    image: "aryhomes.png",
    title: "Ary Homes",
    desc: "Ary Homes is a fullstack real estate application with firebase as a backend service, with features such as authentication, google oAuth, fully functional and detailed admin panel to add edit and delete properties, view all users as well as a blog section, users can also add blog posts which would automatically appear on the site",
    href: "https://aryhomes.netlify.app",
    stacks: "react, sass, redux toolkit, context API firebase",
  },
  {
    image: "pinvent.png",
    title: "Pinvent App",
    desc: "Pinvent is a fullstack inventory application where a user can store and manage products. features include: Full authentication system, and user profiles. Also ability to add, edit products etc",
    href: "https://pinvent.netlify.app",
    stacks: "react, redux toolkit, node js, sass, mongoDB, express",
  },
  {
    image: "nodeopenai.png",
    title: "Image Generator with Open AI",
    desc: "This is a full stack application built with typescript on both Frontend(React) and Backend(Node JS and Express)",
    href: "https://nodeopenai.netlify.app/",
    stacks: "react, nodejs, typescript, express, Open AI (DALL-E),",
  },
  {
    image: "aryhomes.png",
    title: "Ary Homes",
    desc: "Ary Homes is a fullstack real estate application with firebase as a backend service, with features such as authentication, google oAuth, fully functional and detailed admin panel to add edit and delete properties, view all users as well as a blog section, users can also add blog posts which would automatically appear on the site",
    href: "https://aryhomes.netlify.app",
    stacks: "react, sass, redux toolkit, context API firebase",
  },

  {
    image: "shopland.png",
    title: "Shopland E-commerce application",
    desc: "A fullstack e-commerce application with firebase as a backend service, with features such as authentication, google oAuth, admin panel to add edit and delete products as well as change order status which reflects on users page, review section to review products after a purchase, etc. ",
    href: "https://shop-land.netlify.app",
    stacks: "react, sass, redux toolkit, firebase, paystack",
  },
  {
    image: "empdir.png",
    title: "Employee Directory",
    desc: "An applicatio that contains a full log of employees/staffs, ability to filter and sort according to preference, an expense log that contains all expenses made, which can also be filtered and sorted in detail. More detailes explaination of this project can be found in the README file of the repository of this project: https://github.com/Elue-dev/Employee-Directory",
    href: "https://employeedirapp.netlify.app",
    stacks: "react, redux toolkit, react context",
  },
  {
    image: "wworld.png",
    title: "Wisdoms World Blog",
    desc: "A public health platform aimed at sharing common diseases and preventive tips, health quotes etc",
    href: "https://wisdomsworld.netlify.app",
    stacks: "html, css, vanilla javaScript",
  },

  {
    image: "quickshop.png",
    title: "Ecommerce Application",
    desc: "A e-commerce app built with react, firebase for authentication and flutterwave as payment gateway",
    href: "https://quickshopapp.netlify.app",
    stacks: "react w/ context API & useReducers, firebase",
  },
  {
    image: "abnb.png",
    title: "AirBnB like clone",
    desc: "AirBnB like web app built with React and Redux. JSON Web Token (from a backend dev) for user verification.",
    href: "https://abnb.netlify.app",
    stacks: "react, redux, css",
  },
  // {
  //   image: "fintracker.png",
  //   title: "Finance tracker app",
  //   desc: "Simple react app where you can store and track your transactions. The transactions that shows is dependent on the user that is signed in. Homepage is a protected route as well.",
  //   href: "https://financetrackerapp.netlify.app",
  //   stacks: "react w/ context API, firebase",
  // },
  {
    image: "rdirectory.png",
    title: "Recipe app with firebase",
    desc: "Simple app showing a recipe directory where one can add recipes only if they have an account. Other nice features added",
    href: "https://recipedirectoryapp.netlify.app",
    stacks: "react w/ context API, firebase",
  },
  {
    image: "msearch.png",
    title: "Movie Searching App",
    desc: "React application where any movie can be searched, added to favourites and stored in local storage.",
    href: "https://omdbmovieapp.netlify.app",
    stacks: "react, css",
  },
  {
    image: "boon.png",
    title: "Resort landing page",
    desc: "A travel resort landing page, showcasing awesome resorts where people can come to relax or have vacations.",
    href: "https://boonresortblog.netlify.app",
    stacks: "html, css, vanilla javaScript",
  },
  {
    image: "rmorty.png",
    title: "Rick and Morty App",
    desc: "Rick and Morty App built with React and GraphQL",
    href: "https://ricknmortyyapp.netlify.app",
    stacks: "react , css, graphQL",
  },
  {
    image: "microsoft.png",
    title: "Microsoft Homepage  Clone",
    desc: "AirBnB like web app built with React and Redux. JSON Web Token (from a backend dev) for user verification.",
    href: "https://oldmicrosoftclone.netlify.app",
    stacks: "html, css, vanilla javaScript",
  },
  // {
  //   image: "ecommerce.png",
  //   title: "Ecommerce website design",
  //   desc: "Frontend of a mini e-commerce site. ",
  //   href: "https://redstoresite.netlify.app",
  //   stacks: "html , css, vanilla javaScript",
  // },
  {
    image: "numguess.png",
    title: "Number guesser game",
    desc: "A Vanilla JavaScript application where random numbers are guessed until it matches the programmed number.",
    href: "https://jsnumberguessergame.netlify.app",
    stacks: "html, css, vanilla JavaScript",
  },
  {
    image: "gpt3.png",
    title: "GPT-3 Website",
    desc: "A very cool React landing page built with common react method eg props, state, mapping, etc",
    href: "https://gpt3site.netlify.app",
    stacks: "react, css",
  },
];
